export const alphabet = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
];

export interface IUser {
  id: number;
  firstName: string;
  lastName: string;
  phoneNumber: string;
  email: string | null;
}

export const users = [
  {
    id: 1,
    firstName: "Abdul",
    lastName: "Aziz",
    phoneNumber: "+90 552 625 58 84",
    email: "abdulaziz@hotmail.com",
  },
  {
    id: 2,
    firstName: "Ali",
    lastName: "Kamışçı",
    phoneNumber: "+90 567 586 34 63",
    email: null,
  },
  {
    id: 3,
    firstName: "Ahmet",
    lastName: "Ulu",
    phoneNumber: "+90 593 386 25 63",
    email: "ahmetulu@hotmail.com",
  },
  {
    id: 30,
    firstName: "Atalay",
    lastName: "Kayan",
    phoneNumber: "+90 523 436 42 34",
    email: null,
  },
  {
    id: 4,
    firstName: "Bamsı",
    lastName: "Bilgin",
    phoneNumber: "+90 532 385 78 33",
    email: "bamsibilgin@hotmail.com",
  },
  {
    id: 5,
    firstName: "Beyza",
    lastName: "Altın",
    phoneNumber: "+90 535 756 85 84",
    email: "beyzaaltin@hotmail.com",
  },
  {
    id: 6,
    firstName: "Canan",
    lastName: "Haluk",
    phoneNumber: "+90 582 651 65 46",
    email: "cananhaluk@hotmail.com",
  },
  {
    id: 7,
    firstName: "Deniz",
    lastName: "Bilgin",
    phoneNumber: "+90 542 384 34 63",
    email: null,
  },
  {
    id: 8,
    firstName: "Derya",
    lastName: "Derin",
    phoneNumber: "+90 524 438 35 78",
    email: "deryaderin@hotmail.com",
  },
  {
    id: 9,
    firstName: "Efe",
    lastName: "Soylu",
    phoneNumber: "+90 559 325 35 43",
    email: null,
  },
  {
    id: 10,
    firstName: "Fazıl",
    lastName: "Uzun",
    phoneNumber: "+90 553 454 23 46",
    email: null,
  },
  {
    id: 11,
    firstName: "Güney",
    lastName: "Su",
    phoneNumber: "+90 534 646 23 42",
    email: null,
  },
  {
    id: 12,
    firstName: "Hüseyin",
    lastName: "Keskin",
    phoneNumber: "+90 554 656 53 43",
    email: null,
  },
  {
    id: 13,
    firstName: "Ihsan",
    lastName: "Fındık",
    phoneNumber: "+90 564 464 34 33",
    email: null,
  },
  {
    id: 14,
    firstName: "Jale",
    lastName: "Akan",
    phoneNumber: "+90 565 343 24 34",
    email: null,
  },
  {
    id: 15,
    firstName: "Kamil",
    lastName: "Akay",
    phoneNumber: "+90 523 642 34 33",
    email: null,
  },
  {
    id: 16,
    firstName: "Leyla",
    lastName: "Gül",
    phoneNumber: "+90 546 453 32 23",
    email: null,
  },
  {
    id: 17,
    firstName: "Mustafa",
    lastName: "Gür",
    phoneNumber: "+90 546 756 65 87",
    email: null,
  },
  {
    id: 18,
    firstName: "Nazlı",
    lastName: "Işık",
    phoneNumber: "+90 546 756 65 87",
    email: null,
  },
  {
    id: 19,
    firstName: "Osman",
    lastName: "Kuvvet",
    phoneNumber: "+90 534 587 88 07",
    email: null,
  },
  {
    id: 20,
    firstName: "Pelin",
    lastName: "Yürüyen",
    phoneNumber: "+90 534 243 79 82",
    email: null,
  },
  {
    id: 21,
    firstName: "Rana",
    lastName: "Sevilen",
    phoneNumber: "+90 534 098 21 46",
    email: null,
  },
  {
    id: 22,
    firstName: "Semih",
    lastName: "Yan",
    phoneNumber: "+90 534 234 45 23",
    email: null,
  },
  {
    id: 23,
    firstName: "Tülay",
    lastName: "Gözde",
    phoneNumber: "+90 534 325 65 46",
    email: null,
  },
  {
    id: 24,
    firstName: "Umut",
    lastName: "Ula",
    phoneNumber: "+90 534 435 63 43",
    email: null,
  },
  {
    id: 25,
    firstName: "Veli",
    lastName: "Gezen",
    phoneNumber: "+90 534 676 23 32",
    email: null,
  },
  {
    id: 26,
    firstName: "Yaşar",
    lastName: "Bilenen",
    phoneNumber: "+90 534 876 23 57",
    email: null,
  },
  {
    id: 27,
    firstName: "Zekariya",
    lastName: "Öz",
    phoneNumber: "+90 546 454 46 54",
    email: "zekariyaoz@hotmail.com",
  },
];
